repos:
  - repo: local
    hooks:
      - id: update-version
        name: update-version
        entry: python3 -c "from datetime import datetime; print(datetime.now().strftime('%Y%m%d.%H%M%S.%f'))" > version
        language: system