name: Regression

# on:
#   pull_request_review:
#     types: [submitted]
#   workflow_dispatch:

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Regression:
    # if: (github.event.review.state == 'approved') && (github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
    
    container:
      image: public.ecr.aws/certora/cvt-image:2024.10.23-4499-c4f8ad4
    
    env:
      ETHSCAN_API_KEY: ${{ secrets.ETHSCAN_API_KEY }}
      QUORUM_PATH: "."
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Quorum Repo
      run: pip3.11 install .

    - name: Execute Regression Tests
      run: |
        pytest Quorum/tests --maxfail=1 --disable-warnings --tb=short
        CheckProposal --config Quorum/execution.json

