name: "test_steps"
description: "All the steps required for testing the Quorum repository"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      run: pip3 install poetry==1.8.5

    - name: Install Quorum Repo
      shell: bash
      run: poetry install

    - name: Lint with Ruff
      shell: bash
      run: |
        poetry run ruff check src
        poetry run ruff format --check src

    - name: Run unit tests
      shell: bash
      run: poetry run pytest src/quorum/tests --maxfail=1 --disable-warnings --tb=short

    - name: Run Quorum setup
      shell: bash
      run: poetry run quorum setup --working-dir workdir

    - name: Init working directory
      shell: bash
      run: |
        mv src/quorum/tests/regression.json workdir/regression.json
        mv src/quorum/tests/ground_truth.json workdir/ground_truth.json
        echo "ETHSCAN_API_KEY=${ETHSCAN_API_KEY}" >> workdir/.env
        echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> workdir/.env

    - name: Single Address Test
      shell: bash
      working-directory: workdir
      run: poetry run quorum validate-address --protocol-name Aave --chain Ethereum --payload-address 0xAD6c03BF78A3Ee799b86De5aCE32Bb116eD24637

    - name: Batch Test
      shell: bash
      working-directory: workdir
      run: poetry run quorum validate-batch --config regression.json

    - name: Proposal ID Test
      shell: bash
      working-directory: workdir
      run: poetry run quorum validate-by-id --proposal-id 137 --protocol-name Aave

    - name: IPFS Test
      shell: bash
      working-directory: workdir
      run: poetry run quorum validate-ipfs --proposal-id 20 --chain Scroll --payload-address 0x2B25cb729D90630395Cd3140f3460a73A41Fe5f0

    - name: Generate Report
      shell: bash
      working-directory: workdir
      run: poetry run quorum generate-report --proposal_id 137
